{{- $root := . -}}
{{- range .Values.dnsServers }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $root.Values.serviceName }}-pv-{{ .server }}
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ $root.Values.serviceName }}-storage-{{ .server }}
  hostPath:
    path: {{ $root.Values.dataPath }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .server }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $root.Values.serviceName }}-pvc-{{ .server }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ $root.Values.serviceName }}-storage-{{ .server }}
  resources:
    requests:
      storage: 20Gi
---
{{- end }}  