{{- $root := . -}}
{{- range .Values.dnsServers }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $root.Values.serviceName }}-pv-{{ .server }}
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ $root.Values.serviceName }}-storage-{{ .server }}
  hostPath:
    path: {{ $root.Values.dataPath }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .server }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $root.Values.serviceName }}-pvc-{{ .server }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ $root.Values.serviceName }}-storage-{{ .server }}
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ $root.Values.namespace }}
  name: {{ $root.Values.serviceName }}-{{ .server }}
spec:
  serviceName: "{{ $root.Values.serviceName }}-{{ .server }}"
  replicas: 1
  selector:
    matchLabels:
      app: {{ $root.Values.serviceName }}-{{ .server }}
  template:
    metadata:
      labels:
        app: {{ $root.Values.serviceName }}-{{ .server }}
    spec:
      nodeName: {{ .server }}
      containers:
      - image: {{ $root.Values.image.name }}:{{ $root.Values.image.tag }}
        name: {{ $root.Values.serviceName }}
        env:
          - name: default-authentication-plugin
            value: "mysql_native_password"
          - name: MYSQL_ROOT_PASSWORD
            value: "{{ $root.Values.dbPassword }}"
        ports:
        - containerPort: 3306
          name: {{ $root.Values.serviceName }}-{{ .server }}
        volumeMounts:
          - name: {{ $root.Values.serviceName }}-data-{{ .server }}
            mountPath: /var/lib/mysql
      volumes:
        - name: {{ $root.Values.serviceName }}-data-{{ .server }}
          persistentVolumeClaim:
            claimName: {{ $root.Values.serviceName }}-pvc-{{ .server }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $root.Values.serviceName }}-int-{{ .server }}
  namespace: default
spec:
  ports:
    - port: 3306
      protocol: TCP
  selector:
    app: {{ $root.Values.serviceName }}-{{ .server }}
  clusterIP: {{ .ip }}
---
{{- end }}  